### ISSUE TITLE
R package install bugs with make_obis_monthly Github Action

### ISSUE THREAD

**Issue by bbest** [marinebon/p2p#26]
* [make_obis_monthly #5](https://github.com/marinebon/p2p/runs/2759646962?check_suite_focus=true)

```
configure: error: 
--------------------------------------------------------------------------------
  Configuration failed because libudunits2.so was not found. Try installing:
    * deb: libudunits2-dev (Debian, Ubuntu, ...)
    * rpm: udunits2-devel (Fedora, EPEL, ...)
    * brew: udunits (OSX)
  If udunits2 is already installed in a non-standard location, use:
    --configure-args='--with-udunits2-lib=/usr/local/lib'
  if the library was not found, and/or:
    --configure-args='--with-udunits2-include=/usr/include/udunits2'
  if the header was not found, replacing paths with appropriate values.
  You can alternatively set UDUNITS2_INCLUDE and UDUNITS2_LIBS manually.
--------------------------------------------------------------------------------

See `config.log' for more details
ERROR: configuration failed for package ‘units’
```

**Comment by bbest** [comment]
Attempting fix with commit https://github.com/marinebon/p2p/commit/ef95e553bdd736f4ab1cad5df0da470439ea1072 adding:

```yaml
- name: Fix units R package install asdf
        run: |
          apt install libudunits2-dev
```

**Comment by bbest** [comment]
Since running on Mac OSX:

```yaml
  - name: Fix units R package install
     run: |
          brew install udunits
```
