### ISSUE TITLE
docs dir conflicts from travis

### ISSUE THREAD

**Issue by 7yl4r** [marinebon/p2p#4]
Reported by @eqmh : Because travis pushes on the master branch sometimes you can get unexpected merge conflicts. [This article](http://hackwrite.com/posts/github-pages-problem/) describes the problem well (although I disagree with the conclusion).

marinebon/condition-reports force-pushes over a gh-pages branch, but that requires some weird build steps rather than nicely building into ./docs. I would like a better option, but I don't have any examples.

Best way might be to use the actual [travis.yml deployment](https://docs.travis-ci.com/user/deployment/pages/) instead of the manual `git` commands. I think that would look something like:

```yml
deploy:
  local-dir: ./docs
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  target-branch: gh-pages
  on:
    branch: master
```

after doing this is would also make sense to add `./docs` to the `.gitignore`
